#示例

name: "update submodules"

on:
    schedule: 
      - cron: '*/2 * * * *'
    push:
        branches:
            -main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with: 
                submodules: 'recursive'

            - name: update submodules
              run: 
                git submodule update --remote --recursive
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add .
                git commit -m "自动更新子仓库" || echo "无变更"
                git push 